server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entry
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ijajsdasjdasjdasjdkkas"
    valid-duration: 20
    refreshable-duration: 36000
